In [43]:
import pandas as pd
import yfinance as yf
from datetime import datetime

In [44]:
symbols = pd.read_csv("symbols.csv")['Symbol'].tolist()

In [45]:
netAssets = []
inceptionDate = []

for symbol in symbols:
    ticker = yf.Ticker(symbol)
    d = ticker.info

    netAssets.append(d.get("totalAssets"))
    inceptionDate.append(d.get("fundInceptionDate"))



df = pd.DataFrame({
    "Symbol": symbols,
    "Net Assets": netAssets,
    "Inception Date": inceptionDate
})

In [46]:
netAssetsCopy = df.copy()
netAssetsCopy

   Symbol    Net Assets  Inception Date
0     VUG  3.179217e+11    1.075075e+09
1     VOO  1.421127e+12    1.283818e+09
2     IVV  7.205434e+11    9.583488e+08
3     SPY  6.515883e+11    7.276608e+08
4     VTI  1.991754e+12    9.906624e+08
..    ...           ...             ...
95   SOXX  2.059264e+10    9.947232e+08
96    EEM  2.490563e+10    1.049674e+09
97   JAAA  2.667246e+10    1.602806e+09
98    MDY  2.421750e+10    7.995456e+08
99    XLC  2.410815e+10    1.529280e+09

[100 rows x 3 columns]

In [47]:
netAssetsCopy['In Billions'] = netAssetsCopy['Net Assets'] / 1e9
netAssetsCopy.sort_values(by='Inception Date', inplace=True, ascending=False)
netAssetsCopy['Inception Date'] = pd.to_datetime(netAssetsCopy['Inception Date'], unit='s').dt.date
netAssetsCopy.to_csv("net_assets.csv", index=True)

In [48]:
closes = yf.download(symbols, start="2000-01-01", end=datetime.now().strftime("%Y-%m-%d"), auto_adjust = False)['Close']

[*********************100%***********************]  100 of 100 completed

In [49]:
closes.to_csv("closes.csv", index=True)

43,IBIT,53052862464.0,2024-01-05,53.052862464
77,JEPQ,34272116736.0,2022-05-03,34.272116736
82,CGDV,29108258816.0,2022-02-22,29.108258816
97,JAAA,26672459776.0,2020-10-16,26.672459776
29,QQQM,68830765056.0,2020-10-13,68.830765056
28,SGOV,83568402432.0,2020-05-26,83.568402432
57,JEPI,43964334080.0,2020-05-20,43.96433408
80,DYNF,30008514560.0,2019-03-19,30.00851456
83,GLDM,29616130048.0,2018-06-25,29.616130048
99,XLC,24108154880.0,2018-06-18,24.10815488
74,JPST,37516902400.0,2017-05-17,37.5169024
90,IDEV,27528067072.0,2017-03-21,27.528067072
61,VTEB,44200468480.0,2015-08-21,44.20046848
76,IUSB,36142247936.0,2014-06-10,36.142247936
68,DGRO,37549682688.0,2014-06-10,37.549682688
50,QUAL,46515249152.0,2013-07-16,46.515249152
30,BNDX,116905074688.0,2013-05-31,116.905074688
8,IEFA,169633218560.0,2012-10-18,169.63321856
44,IXUS,51986108416.0,2012-10-18,51.986108416
13,IEMG,134083567616.0,2012-10-18,134.083567616
65,GOVT,40681287680.0,2012-02-14,40.68128768
46,SMH,40983896064.0,2011-12-20,40.983896064
27,SCHD,84820000768.0,2011-10-20,84.820000768
14,VXUS,582269730816.0,2011-01-26,582.269730816

In [ ]:
netAssetsCopy = netAssetsCopy[netAssetsCopy['Inception Date'] <= datetime(2011, 1, 1).date()]
goodSymbols = netAssetsCopy['Symbol'].tolist()
goodCloses = closes[goodSymbols]

   Symbol    Net Assets Inception Date  In Billions
64   VONG  4.494878e+10     2010-09-20    44.948783
1     VOO  1.421127e+12     2010-09-07  1421.127057
15   VOOG  2.081877e+10     2010-09-07    20.818772
89   TQQQ  2.459137e+10     2010-02-09    24.591368
45   SCHG  4.841656e+10     2009-12-11    48.416563
..    ...           ...            ...          ...
70    XLV  3.860388e+10     1998-12-16    38.603882
73    XLE  4.360313e+10     1998-12-16    43.603132
56    DIA  4.175968e+10     1998-01-13    41.759683
98    MDY  2.421750e+10     1995-05-04    24.217504
3     SPY  6.515883e+11     1993-01-22   651.588272

[75 rows x 4 columns]